"""Sync models → Postgres schema

Revision ID: 7d94e338fb1c
Revises: ad944b57ed89
Create Date: 2025-06-04 21:23:02.901992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d94e338fb1c'
down_revision: Union[str, None] = 'ad944b57ed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
