"""create exercise_entries table

Revision ID: 940f952b1a36
Revises: 7d94e338fb1c
Create Date: 2025-06-08 17:41:10.672555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940f952b1a36'
down_revision: Union[str, None] = '7d94e338fb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_entries_id'), 'exercise_entries', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_entries_user_id'), 'exercise_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_entries_user_id'), table_name='exercise_entries')
    op.drop_index(op.f('ix_exercise_entries_id'), table_name='exercise_entries')
    op.drop_table('exercise_entries')
    # ### end Alembic commands ###
